controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    
    # Joint State Broadcaster
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    # Joint Position Example Controller (표준 컨트롤러 사용)
    joint_position_example_controller:
      type: arm_controllers/JointPositionExampleController  

# Joint State Broadcaster 설정
joint_state_broadcaster:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

# Joint Position Example Controller 설정
joint_position_example_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
